env:
  DOCKER_COMPOSE_VERSION: 1.24.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - ln -s env.dev.tpl .env

jobs:
  include:
    - stage: "Testing & Linting"
      name: "Markdownlint"
      script:
        - gem install mdl
        - mdl .
    - name: "Pylint"
      script: docker-compose run pycont-api-test pylint --load-plugins=pylint_django pycont
    - name: "Pycodestyle"
      script: docker-compose run pycont-api-test pycodestyle pycont
    - name: "Pydocstyle"
      script: docker-compose run pycont-api-test pydocstyle pycont
    - name: "Eslint"
      script: docker-compose run pycont-ui npm run lint
    - name: "Prettier"
      script: docker-compose run pycont-ui npm run prettier-ci
    - name: "Unit testing"
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - echo UID=$UID >> .env
        - echo GID=$GID >> .env
      script:
        - docker-compose up -d mariadb-test
        - docker-compose run pycont-api-test sh -c "./wait_for_mysql.py && coverage run ./manage.py test tests --noinput --traceback || true; coverage xml"
        # cc-test-reporter prefix / add-prefix are not working as expected,
        # maybe in further versions it will...
        - sed -i 's/\/usr\/src\/app\//api\//g' api/cobertura.xml
        - docker-compose run pycont-ui npm run test-ci
        - sed -i 's/\/usr\/src\/app\//ui\//g' ui/coverage/lcov.info
      after_script:
        - ./cc-test-reporter format-coverage -t cobertura -o coverage-api.json api/cobertura.xml
        - ./cc-test-reporter format-coverage -t lcov -o coverage-ui.json ui/coverage/lcov.info
        - ./cc-test-reporter sum-coverage --output coverage.json --parts 2 coverage-api.json coverage-ui.json
        - ./cc-test-reporter upload-coverage -i coverage.json
