version: '3.7'

networks:
  pycont-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  pycont:
    image: nginx:1
    networks:
      - pycont-net
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/
      - ./api/static/:/opt/pycont/static/

  mariadb:
    image: mariadb:10
    container_name: pycont-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: pycont
      MYSQL_USER: pycont
      MYSQL_PASSWORD: pycont
    restart: on-failure
    networks:
      - pycont-net
    volumes:
      - mariadb_data:/var/lib/mysql

  mariadb-test:
    image: mariadb:10
    container_name: pycont-mariadb-test
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: test_pycont
      MYSQL_USER: pycont
      MYSQL_PASSWORD: pycont
    restart: on-failure
    networks:
      - pycont-net

  pycont-api-base:
    build:
      context: ./api/
      dockerfile: build/Dockerfile.base
    command: /bin/false
    container_name: pycont-api-base
    image: pycont-api-base

  pycont-api:
    build:
      context: ./api/
      dockerfile: build/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8080
    container_name: pycont-api
    depends_on:
      - pycont-api-base
    environment:
      AUTH_COOKIE_SECURE: 0
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: django-secret-key
    expose:
      - "8080"
    image: pycont-api-dev
    networks:
      - pycont-net
    ports:
      - "8081:8080"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/usr/src/app/

  pycont-api-test:
    build:
      context: ./api/
      dockerfile: build/Dockerfile.dev
    command: /bin/false
    container_name: pycont-api-test
    depends_on:
      - pycont-api-base
    environment:
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: django-secret-key
      MYSQL_DB_HOST: mariadb-test
    image: pycont-api-dev
    networks:
      - pycont-net
    stdin_open: true
    tty: true
    user: ${UID}:${GID}
    volumes:
      - ./api/:/usr/src/app/
      - ./setup.cfg:/usr/src/app/setup.cfg

  pycont-ui:
    build:
      context: ./ui/
      dockerfile: build/Dockerfile
    command: npm start
    container_name: pycont-ui
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    image: pycont-ui
    networks:
      - pycont-net
    stdin_open: true
    tty: true
    user: ${UID}:${GID}
    volumes:
      - ./ui/:/usr/src/app/
      - node_modules:/usr/src/app/node_modules/

volumes:
  mariadb_data:
  node_modules:
